FROM arm64v8/python:3.9.16-bullseye
# FROM arm64v8/python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .
COPY asound.conf /etc/asound.conf

RUN mkdir /app/media

# RUN apt-get install -y libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
# RUN sdl-config --cflags --libs
EXPOSE 6000
CMD [ "python3", "-u", "./main.py" ]
# CMD [ "/bin/bash"]