FROM arm64v8/python:3.9.16-bullseye

WORKDIR /app

COPY requirements.txt ./

RUN apt-get update -y && \
    apt-get install -y python3-rpi.gpio && \
    apt-get update && apt-get install -y gcc && \
    apt-get install -y bluetooth bluez
   
RUN pip install -r requirements.txt
RUN pip install --upgrade pip setuptools==52.0.0
RUN python3 -m pip install pybluez

COPY . .

# CMD [ "python3", "-u", "./main.py" ]
# RUN chmod o+rw /var/run/sdp
ENTRYPOINT sh entrypoint.sh
# CMD [ "/bin/bash"]